### ISSUE TITLE
Integração com HikaShop

### ISSUE THREAD

**Issue by alexandreangelis** [gerencianet/gn-api-virtuemart#1]
Assim como eu utilizo para meus clientes o Hikashop tem outros diversos na comunidade Joomla que utiliza o Hikashop. É possível criar essa integração??

https://www.hikashop.com/

https://www.hikashop.com/support/documentation/62-hikashop-developer-documentation.html#payment

**Comment by chuckbnorris** [comment]
@alexandreangelis 

Agradecemos a sugestão, registramos internamente e, em caso de implementação, você poderá conferir em nosso changelog: https://dev.gerencianet.com.br/docs/changelog
